webapp/config/routes.rb
Webapp::Application.routes.draw do
  resources :maps do
    resources :layers
  end

  resources :maps

  devise_for :users

  root :to => 'maps#index'

end

webapp/app/models/map.rb
class Map < ActiveRecord::Base
  has_many :layers, dependent: :destroy
  belongs_to :user
  validates_presence_of :user

  attr_accessible :description, :name

end

webapp/app/controllers/maps_controller.rb
class MapsController < ApplicationController

  # Require the user to login for all actions except index/show
  before_filter :authenticate_user!, :except => [:index, :show]

  # Only allow the map's owner to update/edit or destroy it
  before_filter :only => [:update, :edit, :destroy] do
    @map = Map.find(params[:id])

    if current_user != @map.user
      flash[:error] = "You must be logged in as the owner of this map to modify it"
      redirect_to new_user_session_url
    end
  end

  # GET /maps
  # GET /maps.json
  def index
    @maps = Map.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @maps }
    end
  end

  # GET /maps/1
  # GET /maps/1.json
  def show
    @map = Map.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @map }
    end
  end

  # GET /maps/new
  # GET /maps/new.json
  def new
    @map = current_user.maps.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @map }
    end
  end

  # GET /maps/1/edit
  def edit
  end

  # POST /maps
  # POST /maps.json
  def create
    @map = current_user.maps.new(params[:map])

    respond_to do |format|
      if @map.save
        format.html { redirect_to @map, notice: 'Map was successfully created.' }
        format.json { render json: @map, status: :created, location: @map }
      else
        format.html { render action: "new" }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /maps/1
  # PUT /maps/1.json
  def update
    respond_to do |format|
      if @map.update_attributes(params[:map])
        format.html { redirect_to @map, notice: 'Map was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maps/1
  # DELETE /maps/1.json
  def destroy
    @map.destroy

    respond_to do |format|
      format.html { redirect_to maps_url }
      format.json { head :no_content }
    end
  end
end

webapp/app/helpers/maps_helper.rb
module MapsHelper
end

webapp/app/views/maps/_form.html.erb
<%= form_for(@map) do |f| %>
  <% if @map.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@map.errors.count, "error") %> prohibited this map from being saved:</h2>

      <ul>
      <% @map.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

webapp/app/views/maps/edit.html.erb
<h1>Editing map</h1>

<%= render 'form' %>

<%= link_to 'Edit Layers', map_layers_path(@map) %> |
<%= link_to 'Show', @map %> |
<%= link_to 'Back', maps_path %>

webapp/app/views/maps/index.html.erb
<h1>Listing maps</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @maps.each do |map| %>
  <tr>
    <td><%= map.name %></td>
    <td><%= map.description %></td>
    <td><%= link_to 'Show', map %></td>
    <td><%= link_to 'Edit', edit_map_path(map) %></td>
    <td><%= link_to 'Destroy', map, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Map', new_map_path %>

webapp/app/views/maps/new.html.erb
<h1>New map</h1>

<%= render 'form' %>

<%= link_to 'Back', maps_path %>

webapp/app/views/maps/show.html.erb
<p>
  <b>Name:</b>
  <%= @map.name %>
</p>

<p>
  <b>Description:</b>
  <%= @map.description %>
</p>

<div id="map_options">
  <label>BBox<input type="checkbox" id="bbox" name="bbox" value="bbox" checked="checked"></label>
  <label>Cluster<input type="checkbox" id="cluster" name="cluster" value="cluster" checked="checked"></label>
</div>

<%= tag('div', { class: 'map', id: 'map', data: { id: @map.id, url: map_url(@map) } }) %></div>

<%= link_to 'Layers', map_layers_path(@map) %> |
<%= link_to 'Edit', edit_map_path(@map) %> |
<%= link_to 'Back', maps_path %>